/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Help": "帮助",
    "IdleMaz": "迷宫放置",
    "Journal": "日记",
    "Resources": "资源",
    "Wake Up...": "你醒了...",
    "e": "",
    "OK": "好的",
    "Water": "水",
    "You are thirsty...": "你感到口渴...",
    "You wake up in a strange place. You don't know where you are or how you got here.": "你在一个陌生的地方醒来。 你不知道你在哪里，也不知道你是怎么来到这里的。",
    ". The resources you find along the way are added to your inventory.": ". 您沿途找到的资源将添加到您的库存中。",
    ". With each waymarker you can go one step deeper into the maze. Along the path you collect all the resources you find.": ". 使用每个路标，您可以在迷宫中更深入一步。 沿着这条路，你会收集你找到的所有资源。",
    "...and hungry.": "……以及饥饿。",
    "1. Basic": "1. 基础",
    "2. Multiplicators": "2.乘数",
    "3. Total production:": "三、总产量：",
    "Actions": "动作",
    "An active basic tile": "一个活跃的基本磁贴",
    "An active mltiplicator tile": "活跃的乘法器块",
    "and": "和",
    "click to activate": "点击激活",
    "food": "食物",
    "Food": "食物",
    "Get another waymarker to go deeper into the dungeon to find food.": "获取另一个路标以深入地牢寻找食物。",
    "gives you": "给你",
    "gold": "金币",
    "Gold": "金币",
    "Here is an example maze path with 5 active tiles and 2 inactive tiles. Let's see how the resource production is calculated.": "这是一个示例迷宫路径，其中包含 5 个活动方块和 2 个非活动方块。 让我们看看资源生产是如何计算的。",
    "In the maze you can find resources. Clicking on a tile in the maze adds it to your path of waymarkers": "在迷宫中你可以找到资源。 单击迷宫中的一个方块将其添加到您的路标路径中",
    "It looks like there is water at the entrance. You should go there.": "入口处好像有水。 你应该去那里。",
    "Meditating": "沉思",
    "multiplies your": "乘以你的",
    "needs are met, you can spend your energy on various actions like scavenging for": "需求得到满足，你就可以把精力花在各种行动上，比如寻找",
    "New Action": "新动作",
    "New Waymarker": "新路标",
    "on waymarkers": "在路标上",
    "or hunting for more": "或寻找更多",
    "per second.": "每秒。",
    "production by 2.": "生产 2.",
    "Scavenging": "清理",
    "Spend Gold": "花费金币",
    "Story Journal": "故事日记",
    "The goal is to explore procedurally generated mazes and reach the end": "目标是探索程序生成的迷宫并到达终点",
    "The water is refreshing and you feel better. But you are still hungry... You should find some food.": "水很清新，你感觉更好。 但是你还是很饿……你应该找点吃的。",
    "water": "水",
    "Waymarker": "路标",
    "Waymarker Path": "路标路径",
    "Welcome to IdleMaze!": "欢迎来到 IdleMaze！",
    "When your": "当你的",
    "You can spend": "你可以花",
    "You don't want to walk deeper into the dungeon without some kind of marker to find your way back out.": "你不想在没有某种标记的情况下更深入地牢来找到你回来的路。",
    "You reached the end of the dungeon, but a door closed behind you. You lost access to all your collected resources and the dungeon turns out to be a maze!": "你到达了地牢的尽头，但一扇门在你身后关上了。 您无法访问所有收集的资源，地牢变成了迷宫！",
    "You realize you stand at the start of a dungeon.": "你意识到你站在地牢的起点。",
    "Your basic needs are met. It's time to take action and find a way out of this dungeon.": "您的基本需求得到满足。 是时候采取行动并找到逃离这个地牢的方法了。",
    "Added gold gain per second display.": "添加了每秒显示的金币增益。",
    "Changed the formular for the cost of actions and waymarkers:": "更改了行动和路标成本的公式：",
    "Changed the resource gain/cost formula for actions.": "改变了行动的资源增益/成本公式。",
    "Export Save": "导出保存",
    "Export State": "导出存档",
    "First proof of concept": "第一个概念证明",
    "Fixed maze randomization issues. 10x bonus was always the same at top and bottom, and the general maze randomness was broken due to re-seeding with bad seed.": "修复了迷宫随机化问题。 10 倍的奖励在顶部和底部总是相同的，一般的迷宫随机性由于重新播种坏种子而被打破。",
    "instead of": "代替",
    "Load State": "加载存档",
    "Maze tiles are now hidden and are slowly uncovered during exploration.": "迷宫地块现在是隐藏的，并在探索过程中慢慢发现。",
    "PRESSING THIS BUTTON WILL DELETE ALL PROGRESS": "按下此按钮将删除所有进度",
    "RESET GAME": "重置游戏",
    "shared on reddit": "在 reddit 上分享",
    "Start maze algorithm from portal. Creates more optional paths from the start point.": "从门口开始迷宫算法。 从起点创建更多可选路径。",
    "Exploring": "探索",
    "Foraging": "觅食",
    "Looting": "掠夺",
    "Digging": "挖掘",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "production: ": "生产: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) food$/, '$1 食物'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);